### ISSUE TITLE
关于pyd文件，使用报错情况

### ISSUE THREAD

**Issue by tianshanzhilong** [Python3Spiders/AllNewsSpider#1]
<img width="583" alt="python运行报错情况" src="https://user-images.githubusercontent.com/80507525/111746446-05150600-88c9-11eb-9c5a-803736950bf5.png">
请教这个报错情况，要如何解决，谢谢

**Comment by inspurer** [comment]
具体报什么错误

**Comment by tianshanzhilong** [comment]
正文内容中有截图的错误提示，直接截图了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Python3Spiders/AllNewsSpider"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月20日(星期六) 晚上6:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Python3Spiders/AllNewsSpider] 关于pyd文件，使用报错情况 (#1)





 
具体报什么错误

**Comment by inspurer** [comment]
你把这个 runner.py 放到 tencent_news_spider 文件夹里去，最好用 pycharm，idle 不一定能识别出

**Comment by tianshanzhilong** [comment]
已把这个 runner.py 放到 tencent_news_spider 文件夹里去，通过 pycharm&nbsp;打开后，进行运行，还是报一样的错误
如图所示






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Python3Spiders/AllNewsSpider"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月21日(星期天) 下午2:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Python3Spiders/AllNewsSpider] 关于pyd文件，使用报错情况 (#1)





 
你把这个 runner.py 放到 tencent_news_spider 文件夹里去，最好用 pycharm，idle 不一定能识别出

**Comment by inspurer** [comment]
用 
from tencent_news_spider import main
main() 
试试

再不行就百度一下 pycharm add source root

**Comment by tianshanzhilong** [comment]
还是不行
看来就只能百度一下了






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Python3Spiders/AllNewsSpider"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月21日(星期天) 晚上9:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Python3Spiders/AllNewsSpider] 关于pyd文件，使用报错情况 (#1)





 
用
 from tencent_news_spider import main
 main()
 试试
 
再不行就百度一下 pycharm add source root

**Comment by inspurer** [comment]
可以看下这个 https://github.com/Python3Spiders/AllNewsSpider/issues/4
