### ISSUE TITLE
pyd module找不到问题

### ISSUE THREAD

**Issue by yingdanlu** [Python3Spiders/AllNewsSpider#2]
您好，感谢构建爬虫。在使用thetime爬虫的时候已经把thetime_news_spider.pyd跟runner.py放到一个目录里面了，但是还是显示No module named 'thetime_news_spider'。求解答！

<img width="1094" alt="Screen Shot 2021-04-03 at 3 12 56 PM" src="https://user-images.githubusercontent.com/15639836/113471504-4d1e5600-948f-11eb-864b-662149bbfd1d.png">

**Comment by inspurer** [comment]
可以考虑将路径加入环境变量

**Comment by inspurer** [comment]
也可以看下这个 https://github.com/Python3Spiders/AllNewsSpider/issues/4
