### ISSUE TITLE
可以考虑分享源码吗？

### ISSUE THREAD

**Issue by Rvlis** [Python3Spiders/AllNewsSpider#7]
@inspurer作者你好，非常感谢你的分享。
我注意到sina和tencent新闻爬取的分类只有科技、娱乐、军事和财经四类，我想请问有办法把所有的分类爬取下来吗，譬如体育、汽车、教育等等。另外，除了.pyd文件外，您可以分享下源码吗，谢谢。

**Comment by inspurer** [comment]
可以把所有分类爬下来，后期成熟可能会开源
