### ISSUE TITLE
版本正确后dll仍然报错

### ISSUE THREAD

**Issue by awxiaoxian2020** [Python3Spiders/AllNewsSpider#8]
![QQ截图20210922151309](https://user-images.githubusercontent.com/69554233/134299053-a9d3ed10-a255-4ff8-8c6a-737e050952fd.png)
似乎无法识别pyd文件

**Comment by inspurer** [comment]
需要 Python 3.6 64 位，你应该是下的是 32 位的

**Comment by awxiaoxian2020** [comment]
32位和64位我都试过了

**Comment by awxiaoxian2020** [comment]
> 需要 Python 3.6 64 位，你应该是下的是 32 位的

32和64我都试过了

**Comment by inspurer** [comment]
> > 需要 Python 3.6 64 位，你应该是下的是 32 位的
> 
> 32和64我都试过了

Mac Os？

**Comment by awxiaoxian2020** [comment]
未使用pycharm，而是使用vscode,成功运行代码
