### ISSUE TITLE
纽约时报爬取失败

### ISSUE THREAD

**Issue by PantheraTigrisAltaica** [Python3Spiders/AllNewsSpider#9]
![1641401308(1)](https://user-images.githubusercontent.com/78310468/148256069-777a36a9-0abf-49c5-b187-4736de6589cb.png)

您好，尝试爬取纽约时报的时候，运行了一下就自动终止了。尝试过不同的关键词和起止日期，都是一样的错误（如图）

能否帮忙看下？谢谢

**Comment by awxiaoxian2020** [comment]
我也遇到了同样的问题

**Comment by inspurer** [comment]
站点小有改动，有机会重构下，平常太忙了，身兼数职，感谢关注。
